# Generated by Django 5.0.3 on 2024-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость')),
            ],
        ),
    ]
